# All environments
spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://demo-postgres:5432/demo
    username: demo
    password: demo
  jpa:
    showSql: true
    hibernate:
      ddlAuto: none
#    properties:
#      hibernate:
#        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
#        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#      org:
#        hibernate:
#          flushMode: COMMIT

    database-platform: org.hibernate.dialect.PostgreSQL9Dialect # because we disable feature detection above

server:
  port: 8443
  ssl:
    key-alias: wightmanSSL
    key-store-password: password
    key-store: classpath:wightmanSSL.p12
    key-store-type: pkcs12
    key-password: password

http:
  port: 8080
